name: Download Firmware

on:
  workflow_dispatch:

  schedule:
    - cron:  '0 8 * * *'

jobs:
  download:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Caching npm dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Download
        run: npm run download

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add firmware/* mdrdownload.json
          git diff-index --cached --quiet HEAD -- || (git commit -m "auto download firmware" && git push)