name: Download Firmware

on:
  workflow_dispatch:

  schedule:
    - cron:  '0 8 * * 3'

jobs:
  download:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download
        run: sed -nE "1,/^\| +Model +\| +categoryID +\| +serviceID +\| +HTTPS +\|$/d; /^\| +-+ +\| +-+ +\| +-+ +\| +-+ +\|$/n;p" README.md | cut -f2 -d'|' | sed -E "s|^ +||g;s| +$||g" | xargs -I{} ./mirror "{}"

      - name: Commit files
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions-user@users.noreply.github.com"
          git add assets/*
          git diff-index --cached --quiet HEAD -- || (git commit -m "auto download firmware" && git push)
